### ISSUE TITLE
Add project skeleton

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/demu#2]
We can introduce some tests in order to restrict the scope of the project

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#3](https://github.com/objectionary/demu/issues/3) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo the only puzzle [#3](https://github.com/objectionary/demu/issues/3) is solved here.
